### ISSUE TITLE
Quantizing for PULP-NN support

### ISSUE THREAD

**Issue by MiguelCosta94** [pulp-platform/pulp-nn#4]
Hi,

I am trying to quantize a simple CNN to run it on a PULP core using PULP-NN. However, I am facing some difficulties to find a suitable quantization strategy as weights and bias should be signed integers, while activations should be in an unsigned integer format. It appears to me that my original CNN should have a "relu" like activation at the end of each convolutional or dense layer to clip negative values to 0. However this is not a solution to my CNN as I have layers directly connected to other layers without any activation in-between. That said, I have negative activations flowing among layers. Can someone share some insights on how to properly quantize a neural network for PULP-NN?

**Comment by FrancescoConti** [comment]
Hi @MiguelCosta94 . Back-to-back linear (e.g., CONV and FC) layers are not directly supported in PULP-NN. There are essentially two reasons:
 - one related to the math: N back-to-back entirely linear layers can always be collapsed into a single linear layer, meaning that they are no more expressive than that. There might be an advantage in keeping them separate (such as, reduce number of operations) but usually a network with non-linear activations in between is more expressive using essentially the same number of operations. So we tend not to use this case at all in our own examples.
 - the other reason is more practical and driven by quantization, which is essentially clipping + dividing in quantization "steps". Usually you combine this with activation, and it is significantly easier to do it properly if you use ReLU or ReLU6. In the former case, you have to replace the ReLU with clipping by "calibrating" the upper side to a reasonable value. In the latter, the ReLU6 is already a clipping function. If you do not have an activation function, such as in the case of back-to-back linear layers, you should still add clipping, but then it has to be calibrated on both sides, which is a bit more delicate (especially to deal with asymmetry). Our solution in the rare cases where we really needed this is to transform the network so that the "low-side clipping" is absorbed by one of the adjacent layers as a bias, therefore yielding a non-negative activation that can be represented as unsigned int. But it is an ad-hoc solution that we applied on a case by case basis.

For all these reasons, purely signed functions have been very low priority so far (we do not use them). At present, we mainly use PULP-NN as lower end of a flow starting from https://github.com/pulp-platform/nemo/ (quantization) and passing through https://github.com/pulp-platform/dory (data tiling), which follows the reasoning above. That said, we definitely might add purely signed functions in the future, but I have no timeline to give for that. It's not that difficult probably, you just have to replace the unsigned vectors with signed ones on the activation side and use the signed version of the various builtins.
However, my personal suggestion is to simply add ReLUs and retrain the network to make your life easier...

**Comment by MiguelCosta94** [comment]
Hi @FrancescoConti . Thanks for your reply. I was able to modify the PULP-NN to support signed ints for a fixed 8-bit precision.
